[package]
name = "RustSafe"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
hex = "0.4.3"
rand = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.9"
